# https://www.techiediaries.com/python-unit-tests-github-actions/
name: Run Python Tests
on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests with pytest
        run: |
          echo "The Path - $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          echo "The Workspace - $GITHUB_WORKSPACE"
          echo "The Ref $GITHUB_REF"
          echo "The csv path $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/blob/master/test_acronyms.csv"
          echo "The file - $DATA_URL"
          echo "The file - $DATA_URL1"
          # pytest tests_wtf.py          
        env:
          FLASK_APP: wtf.py
          DATA_URL: $(GITHUB_SERVER_URL)/$(GITHUB_REPOSITORY)/blob/master/test_acronyms.csv
          DATA_URL1: $GITHUB_SERVER_URL
          FLASK_DEBUG: 1
          SLACK_TOKENS: A,B
