# https://www.techiediaries.com/python-unit-tests-github-actions/
name: Run Python Tests
on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests with pytest
        run: echo "The URL - ${{DATA_URL}}"
        run: echo "The Path - ${{GITHUB_ACTION_PATH}}"
        run: pytest tests_wtf.py
        env:
          FLASK_APP: wtf.py
          FLASK_DEBUG: 1
          DATA_URL: https://raw.githubusercontent.com/michael-barlow3/py_tests/master/test_acronyms.csv
          SLACK_TOKENS: A,B